### ISSUE TITLE
[Conflict/Error​​ ] The newly added front-end MOD has encountered a conflict issue

### ISSUE THREAD

**Issue by zero-wht** [CERBON-MODS/Talk-Balloons#9]
After updating to the latest version, a new required dependency MOD, ​​Modern Networking​​, was added. However, upon launching, it became incompatible with ​​Kotlin for Forge​​, causing the game to fail to start.

[The output before the game crashed..txt](https://github.com/user-attachments/files/20348874/The.output.before.the.game.crashed.txt)

**Comment by zero-wht** [comment]
[Error report-2025-5-20_22.00.35.zip](https://github.com/user-attachments/files/20349264/Error.report-2025-5-20_22.00.35.zip)

**Comment by BluSpring** [comment]
I swear, Forge is actually the worst piece of software ever cursed upon us.

**Comment by zero-wht** [comment]
This is indeed bad, but currently there are many MODs in the package that require his support.

**Comment by BluSpring** [comment]
Should be fixed in the newest version of Modern Networking.

**Comment by WimpieRatte** [comment]
Wow - just as I was encountering this issue (while trying to build a new version for my modpack), I see the issue was resolved literally within the minutes of me trying to troubleshoot it.
Happy :D

**Comment by WimpieRatte** [comment]
Hmm... still getting other crashes because of the added Modern Networking mod, so rather removing the talk balloons mod until those issues are fixed. (Neoforge 1.21.1)

**Comment by BluSpring** [comment]
Creating a new issue and uploading the log there (preferably on the Modern Networking repo) would be nice, I'll look into it in the morning

**Comment by WimpieRatte** [comment]
Will do so at earliest convenience. Should be possible tonight sometime.

**Comment by zero-wht** [comment]
> 嗯。。。由于添加了 Modern Networking mod，仍然会遇到其他崩溃，因此宁愿删除 talk balloons mod，直到这些问题得到解决。（Neoforge 1.21.1）

Yes, it's still a pity that it crashes

[错误报告-2025-5-21_0.27.07.zip](https://github.com/user-attachments/files/20351846/-2025-5-21_0.27.07.zip)

**Comment by WimpieRatte** [comment]
Here's another link to a crash file.
It makes it look like a different mod is the cause. (In my case, Living Things)

https://gnomebot.dev/paste/mclogs/K2mpPL1

**Comment by BluSpring** [comment]
oh my god.

okay, after looking into it, the cause behind this error is because of me shading Kotlin into Modern Networking.
***UNFORTUNATELY***, because Kotlin for Forge is on an outdated version on older versions of Forge, I have to relocate it. Which obviously doesn't end up working for other mods because the API is unaware of this relocation.

For reference:
- ModernNetworking's Kotlin version: 2.1.20
- KotlinForForge on 1.21.1+: 2.1.20
- KotlinForForge on 1.20.1/1.20.4: 2.0.0
- KotlinForForge on 1.18.2/1.19.2: 1.8.21

Another problem is if you include 2 of the same class in 2 different mods on Forge, it will actively panic about it and throw an exception. This is not a problem on Fabric. The only fix for this I have though is to *require* Kotlin for Forge as a dependency. I hope that doesn't break anything.

**Comment by BluSpring** [comment]
Should be fixed now on Modern Networking. Unfortunate that I have to set a dependency on Kotlin for Forge.

**Comment by WimpieRatte** [comment]
Thank you for your quick responses, resolutions and detailed investigations.
Gained huge respect for you because of that.
